project_id = "fhamgdtnxssmmsdfalum"

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false
