project_id = "fhamgdtnxssmmsdfalum"

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.accept-portal-invitation]
verify_jwt = false

[functions.send-portal-invitation]
verify_jwt = false
